name: CI/CD workflow

env:
  SERVER_IP: '151.80.119.61'
  SERVER_USER: root

on:
  push:
    branches:
      - main

jobs:
  check-tests-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Installer Node.js
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
          cache-dependency-path: ./server/package-lock.json

      - name: Install dependencies
        run: npm ci --cache .npm --prefer-offline

      - name: Vérifier le code
        run: npm run lint

      - name: Vérifier les vulnérabilités des dépendances
        run: npm audit

      - name: Exécuter les tests
        run: npm run test:ci

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  check-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Installer Node.js
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
          cache-dependency-path: ./client/package-lock.json

      - name: Install dependencies
        run: npm ci --cache .npm --prefer-offline

      - name: Vérifier le code
        run: npm run lint

      - name: Vérifier les vulnérabilités des dépendances
        run: npm audit

  build-frontend:
    needs: [check-frontend]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Installer Node.js
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
          cache-dependency-path: ./client/package-lock.json

      - name: Install dependencies
        run: npm ci --cache .npm --prefer-offline

      - name: Build application frontend
        run: npm run build

      - name: Upload build artefact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: ./client/dist

  test_e2e:
    needs: [build-frontend]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Installer Node.js
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Installer les dépendances client
        run: |
          cd client
          npm ci --prefer-offline

      - name: Build le frontend
        run: |
          cd client
          npm run build:e2e

      - name: Installer les dépendances serveur
        run: |
          cd server
          npm ci --prefer-offline

      - name: Lancer le serveur backend
        run: |
          cd server
          node index.js &

      - name: Cypress
        uses: cypress-io/github-action@v6
        with:
          working-directory: client
          browser: chrome
          start: npm run preview
          wait-on: http://localhost:4173
          wait-on-timeout: 60
          config: baseUrl=http://localhost:4173

      - name: Upload du rapport de couverture sur Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  deploy:
    needs: [check-tests-backend, test_e2e]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout le code
        uses: actions/checkout@v4

      - name: Download build artefact
        uses: actions/download-artifact@v3
        with:
          name: build
          path: ./dist

      - name: Déployer sur le serveur
        env:
          SERVER_IP: ${{ env.SERVER_IP }}
          SERVER_USER: ${{ env.SERVER_USER }}
        run: |
          eval $(ssh-agent -s)
          ssh-add - <<< "${{ secrets.SSH_KEY_VPS }}"
          mkdir -p ~/.ssh
          ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts
          scp -r ./server $SERVER_USER@$SERVER_IP:/var/www
          scp -r ./dist $SERVER_USER@$SERVER_IP:/var/www
          ssh $SERVER_USER@$SERVER_IP "cd /var/www && npm install --omit=dev"
          ssh $SERVER_USER@$SERVER_IP "cd /var/www && pm2 startOrRestart ecosystem.config.js --env production && pm2 save"
